version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - mastermind-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:${PORT}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - mastermind-network
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/mastermind
      - PORT=${PORT}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mastermind-network
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mastermind-network:
    driver: bridge

volumes:
  mongodb_data:
