name: mastermind CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # -----------------------------------
      # Build & Test Backend
      # -----------------------------------
      - name: Install & Build Backend
        working-directory: ./backend
        run: |
          npm ci
          npm install globals@^15.14.0 --save-dev
          npm run lint
          npm run build

      # (Optionally run tests here if you have them)
      # - name: Run Tests (Backend)
      #   working-directory: ./backend
      #   run: npm run test

      # -----------------------------------
      # Build & Test Frontend
      # -----------------------------------
      - name: Install & Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm install globals@^15.14.0 --save-dev
          npm run lint
          npm run build

      # (Optionally run tests here if you have them)
      # - name: Run Tests (Frontend)
      #   working-directory: ./frontend
      #   run: npm run test

      # -----------------------------------
      # Docker Build and Push
      # -----------------------------------
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/mastermind-backend:latest ./backend
          docker push ghcr.io/${{ github.repository }}/mastermind-backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/mastermind-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository }}/mastermind-frontend:latest
